baseURL = "https://example.com/"
languageCode = "tr-tr"
title = "Cengizhan Akg√ºn Blog"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  disableThemeToggle = false